# Generated by Django 4.2.4 on 2023-08-05 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField()),
                ('last_name', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('poster', models.URLField()),
                ('length_minutes', models.IntegerField()),
                ('release_date', models.DateTimeField()),
                ('description', models.TextField()),
                ('amazon_link', models.URLField()),
                ('cast', models.ManyToManyField(db_table='movie_cast', related_name='appeared_in', to='movies.person')),
                ('directed_by', models.ManyToManyField(db_table='movie_directors', related_name='directed', to='movies.person')),
            ],
        ),
    ]
