# Generated by Django 4.2.4 on 2023-08-05 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='amazon_link',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='movie',
            name='cast',
            field=models.ManyToManyField(blank=True, db_table='movie_cast', default=None, related_name='appeared_in', to='movies.person'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='movie',
            name='directed_by',
            field=models.ManyToManyField(blank=True, db_table='movie_directors', default=None, related_name='directed', to='movies.person'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='length_minutes',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='movie',
            name='poster',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='movie',
            name='release_date',
            field=models.DateField(blank=True, default=None),
        ),
    ]
