# Generated by Django 4.2.5 on 2023-09-11 01:19

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movies', '0002_list_userstreamingplatform_userlist_movielist_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movielist',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 10, 20, 19, 25, 898030)),
        ),
        migrations.AlterField(
            model_name='list',
            name='id',
            field=models.UUIDField(default=uuid.UUID('8f308539-a373-4a83-abd8-4c51aa9f113f'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='UserWatchedMovies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_watched', models.DateTimeField(default=datetime.datetime(2023, 9, 10, 20, 19, 25, 927348))),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.movie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'movies_user_watched_movies',
            },
        ),
    ]
