# Generated by Django 4.2.4 on 2023-08-08 13:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_adjust_fields_for_nullable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='release_date',
            field=models.DateField(blank=True, default=datetime.date(1, 1, 1)),
        ),
    ]
