# Generated by Django 4.2.5 on 2023-09-11 01:33

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_movielist_date_added_alter_list_id_userwatchedmovies'),
    ]

    operations = [
        migrations.AddField(
            model_name='movielist',
            name='date_watched',
            field=models.DateTimeField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='list',
            name='id',
            field=models.UUIDField(default=uuid.UUID('357ca007-7c27-4467-8c9a-2290a0bdca9e'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='movielist',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 10, 20, 33, 32, 58347)),
        ),
        migrations.AlterField(
            model_name='userwatchedmovies',
            name='date_watched',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 10, 20, 33, 32, 79134)),
        ),
    ]
