# Generated by Django 4.2.5 on 2023-09-11 01:41

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0005_remove_user_lists_alter_user_id'),
        ('movies', '0004_movielist_date_watched_alter_list_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='user_id',
            field=models.ForeignKey(default='3d8e9e65-9edf-4eca-8924-60e7686a410a', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='list',
            name='id',
            field=models.UUIDField(default=uuid.UUID('8cde447c-b5d5-4126-b01a-ad73a4f3d53b'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='movielist',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 10, 20, 40, 19, 702662)),
        ),
        migrations.AlterField(
            model_name='userwatchedmovies',
            name='date_watched',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 10, 20, 40, 19, 702880)),
        ),
        migrations.DeleteModel(
            name='UserList',
        ),
    ]
