# Generated by Django 4.2.5 on 2023-09-11 01:51

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_list_user_id_alter_list_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='id',
            field=models.UUIDField(default=uuid.UUID('3f76ab5b-56fb-4334-b0c0-decc149dbe0a'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='movielist',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 10, 20, 51, 50, 121221)),
        ),
        migrations.AlterField(
            model_name='movielist',
            name='date_watched',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='userwatchedmovies',
            name='date_watched',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 10, 20, 51, 50, 121640)),
        ),
    ]
