# Generated by Django 4.2.4 on 2023-10-15 21:22

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_alter_list_id_alter_movielist_date_added_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='id',
            field=models.UUIDField(default=uuid.UUID('edeaf646-1262-4312-bfe2-cc60874db211'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='movielist',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 15, 16, 22, 40, 786322)),
        ),
        migrations.AlterField(
            model_name='userwatchedmovies',
            name='date_watched',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 15, 16, 22, 40, 786465)),
        ),
    ]
