# Generated by Django 4.2.5 on 2023-10-15 21:24

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_alter_list_id_alter_movielist_date_added_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='id',
            field=models.UUIDField(default=uuid.UUID('ce80d2dd-f145-433d-bbf0-f97e42510d4f'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='movielist',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 15, 16, 24, 54, 372937)),
        ),
        migrations.AlterField(
            model_name='userwatchedmovies',
            name='date_watched',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 15, 16, 24, 54, 373156)),
        ),
    ]
