migrate:
	docker-compose exec backend poetry run ./manage.py migrate

makemigrations:
	docker-compose exec backend poetry run ./manage.py makemigrations

super:
	docker-compose exec backend poetry run ./manage.py createsuperuser