INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (1, 'Can add genre', 1, 'add_genre');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (2, 'Can change genre', 1, 'change_genre');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (3, 'Can delete genre', 1, 'delete_genre');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (4, 'Can view genre', 1, 'view_genre');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (5, 'Can add movie', 2, 'add_movie');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (6, 'Can change movie', 2, 'change_movie');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (7, 'Can delete movie', 2, 'delete_movie');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (8, 'Can view movie', 2, 'view_movie');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (9, 'Can add movie cast and crew', 3, 'add_moviecastandcrew');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (10, 'Can change movie cast and crew', 3, 'change_moviecastandcrew');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (11, 'Can delete movie cast and crew', 3, 'delete_moviecastandcrew');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (12, 'Can view movie cast and crew', 3, 'view_moviecastandcrew');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (13, 'Can add streaming platform', 4, 'add_streamingplatform');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (14, 'Can change streaming platform', 4, 'change_streamingplatform');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (15, 'Can delete streaming platform', 4, 'delete_streamingplatform');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (16, 'Can view streaming platform', 4, 'view_streamingplatform');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (17, 'Can add streaming platform movies', 5, 'add_streamingplatformmovies');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (18, 'Can change streaming platform movies', 5, 'change_streamingplatformmovies');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (19, 'Can delete streaming platform movies', 5, 'delete_streamingplatformmovies');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (20, 'Can view streaming platform movies', 5, 'view_streamingplatformmovies');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (21, 'Can add person', 6, 'add_person');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (22, 'Can change person', 6, 'change_person');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (23, 'Can delete person', 6, 'delete_person');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (24, 'Can view person', 6, 'view_person');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (25, 'Can add movie genre', 7, 'add_moviegenre');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (26, 'Can change movie genre', 7, 'change_moviegenre');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (27, 'Can delete movie genre', 7, 'delete_moviegenre');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (28, 'Can view movie genre', 7, 'view_moviegenre');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (29, 'Can add user', 8, 'add_user');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (30, 'Can change user', 8, 'change_user');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (31, 'Can delete user', 8, 'delete_user');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (32, 'Can view user', 8, 'view_user');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (33, 'Can add log entry', 9, 'add_logentry');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (34, 'Can change log entry', 9, 'change_logentry');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (35, 'Can delete log entry', 9, 'delete_logentry');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (36, 'Can view log entry', 9, 'view_logentry');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (37, 'Can add permission', 10, 'add_permission');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (38, 'Can change permission', 10, 'change_permission');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (39, 'Can delete permission', 10, 'delete_permission');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (40, 'Can view permission', 10, 'view_permission');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (41, 'Can add group', 11, 'add_group');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (42, 'Can change group', 11, 'change_group');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (43, 'Can delete group', 11, 'delete_group');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (44, 'Can view group', 11, 'view_group');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (45, 'Can add content type', 12, 'add_contenttype');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (46, 'Can change content type', 12, 'change_contenttype');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (47, 'Can delete content type', 12, 'delete_contenttype');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (48, 'Can view content type', 12, 'view_contenttype');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (49, 'Can add session', 13, 'add_session');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (50, 'Can change session', 13, 'change_session');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (51, 'Can delete session', 13, 'delete_session');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (52, 'Can view session', 13, 'view_session');
