INSERT INTO public.movies_genre (id, name, slug) VALUES (1, 'Sci-Fi', 'sci-fi');
INSERT INTO public.movies_genre (id, name, slug) VALUES (2, 'Virus', 'virus');
INSERT INTO public.movies_genre (id, name, slug) VALUES (3, 'Comedy', 'comedy');
INSERT INTO public.movies_genre (id, name, slug) VALUES (4, 'Haunted House', 'haunted-house');
INSERT INTO public.movies_genre (id, name, slug) VALUES (5, 'Paranoia', 'paranoia');
INSERT INTO public.movies_genre (id, name, slug) VALUES (6, 'Thriller', 'thriller');
INSERT INTO public.movies_genre (id, name, slug) VALUES (7, 'Monster', 'monster');
INSERT INTO public.movies_genre (id, name, slug) VALUES (8, 'Ghosts', 'ghosts');
INSERT INTO public.movies_genre (id, name, slug) VALUES (9, 'Slasher', 'slasher');
INSERT INTO public.movies_genre (id, name, slug) VALUES (10, 'Found Footage', 'found-footage');
INSERT INTO public.movies_genre (id, name, slug) VALUES (11, 'Lovecraftian', 'lovecraftian');
INSERT INTO public.movies_genre (id, name, slug) VALUES (12, 'Possession', 'possession');
INSERT INTO public.movies_genre (id, name, slug) VALUES (13, 'Gothic', 'gothic');
INSERT INTO public.movies_genre (id, name, slug) VALUES (14, 'Zombie', 'zombie');
INSERT INTO public.movies_genre (id, name, slug) VALUES (15, 'Demon', 'demon');
INSERT INTO public.movies_genre (id, name, slug) VALUES (16, 'Gore', 'gore');
INSERT INTO public.movies_genre (id, name, slug) VALUES (17, 'Survival', 'survival');
INSERT INTO public.movies_genre (id, name, slug) VALUES (18, 'Home Invasion', 'home-invasion');
INSERT INTO public.movies_genre (id, name, slug) VALUES (19, 'Cannibalism', 'cannibalism');
INSERT INTO public.movies_genre (id, name, slug) VALUES (20, 'Body Horror', 'body-horror');
INSERT INTO public.movies_genre (id, name, slug) VALUES (21, 'Alien', 'alien');
INSERT INTO public.movies_genre (id, name, slug) VALUES (22, 'Post Apocalypse', 'post-apocalypse');
INSERT INTO public.movies_genre (id, name, slug) VALUES (23, 'Isolation', 'isolation');
INSERT INTO public.movies_genre (id, name, slug) VALUES (24, 'Folk Horror', 'folk-horror');
