import React from 'react'
import './globals.css'
import type { Metadata } from 'next'
import { Epilogue, Inter, Poppins } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

const epilogue = Epilogue({
  subsets: ['latin'],
  variable: '--headingFont',
  display: 'swap'
})

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700', '800'],
  variable: '--primaryFont',
  display: 'swap'
})

const RootLayout = ({
  children
}: {
  children: React.ReactNode
}): JSX.Element => {
  return (
      <html lang="en" className={`${poppins.className} ${epilogue.className}`}>
          <body className={`${poppins.className} ${epilogue.className} ${inter.className}`}>{children}</body>
      </html>
  )
}

export default RootLayout
