# Generated by Django 4.2.5 on 2023-09-11 00:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_list_userstreamingplatform_userlist_movielist_and_more'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='lists',
            field=models.ManyToManyField(blank=True, default=None, related_name='+', through='movies.UserList', to='movies.list'),
        ),
        migrations.AddField(
            model_name='user',
            name='streaming_platforms',
            field=models.ManyToManyField(blank=True, default=None, related_name='+', through='movies.UserStreamingPlatform', to='movies.streamingplatform'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('b6c06222-3497-4e93-9451-e0712a2a4970'), editable=False, primary_key=True, serialize=False),
        ),
    ]
