# Generated by Django 4.2.5 on 2023-09-11 01:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_lists_user_streaming_platforms_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('82c6c0ce-15da-4e69-8ade-74f6900d020e'), editable=False, primary_key=True, serialize=False),
        ),
    ]
