# Generated by Django 4.2.5 on 2023-09-11 01:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_movielist_date_watched_alter_list_id_and_more'),
        ('users', '0003_alter_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='watched_movies',
            field=models.ManyToManyField(blank=True, default=None, related_name='+', through='movies.UserWatchedMovies', to='movies.movie'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('dd0581f9-c8ef-415a-8d52-517aa2017a51'), editable=False, primary_key=True, serialize=False),
        ),
    ]
