# Generated by Django 4.2.5 on 2023-09-11 01:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_watched_movies_alter_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='lists',
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('0841c046-5ca4-4a81-a483-13a050473547'), editable=False, primary_key=True, serialize=False),
        ),
    ]
