# Generated by Django 4.2.5 on 2023-09-11 01:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_user_lists_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('cb64e6f7-e927-43e7-8bd5-b4e3f47776b2'), editable=False, primary_key=True, serialize=False),
        ),
    ]
