# Generated by Django 4.2.4 on 2023-10-15 21:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('b4d026f6-5be9-49f0-b064-9fc82f79be82'), editable=False, primary_key=True, serialize=False),
        ),
    ]
