# Generated by Django 4.2.5 on 2023-10-15 21:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('a2c7b212-662f-4907-a53f-af2e73cf1197'), editable=False, primary_key=True, serialize=False),
        ),
    ]
